### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by marksev1** [patrickjquinn/P-Brain.ai#1]
Cool project! 

Got a few questions.  Will you set up gitter or something for chats about the project?

Does the system always-listen or does it deduce a hotword locally? Since it would be nice if ti weren't listening always ("snowboy" software could be used for local hotword generation). 

It uses Google for STT and TTS, right?

For video 4 you could maybe display a skill that communicates with a device, for example MQTT protocol is the most popular protocol for home automation for makers, for controlling devices...So would be nice if you showed a MQTT skill. 

Could it work "headless"?

Also how come it doesn't detect the "hotword" or the sentence in the first go in your video? You have to say twice all the time. Maybe you could buy a PS3 cam (it is very cheap) which has a 4-mic array, that one will give you way better audio.

What about interacting with the linux-shell or starting programs (mplayer with an url pointing to a mp3 podcast for example)?

**Comment by patrickjquinn** [comment]
Q1: Cool Project - Why thank you!

Q2: I hadn't thought that far ahead but I can do that tonight for sure!

Q3: Yes always listening for the moment, the plan is to move entirely to PocketSphinx.js which allow enable it to only listen for commands when it hears a keyword. It will also mean that the entire voice recognition portion of things will be done locally.

Q4: At the moment, yes Google's TTS & STT is in use but moving that away to a local & open system (See above)

Q5: I will of course make a sample Skill that communicates with devices over MQTT. I've a smart Thermostat here in my apartment that would make for a perfect test case 👍 

Q6: Headless is in the works, once PocketSphinx.js is in place you should be able to pass a simple --headless argument to the server when starting and run it without the UI! My ultimate goal is to make a portable Pebble Core like device using the RasPi Zero, a Lipo battery and a teeny tiny case, so it will need to be able to run headlessly.

Q7: 3 reasons for this, crappy MacBook mic, the fact that the mic is also being used to record audio for the video and poor internet connection (Because we are using the cloud based Google voice api). I'll be picking up one of these: https://www.amazon.com/Kinobo-Microphone-Condenser-Laptop-Computer/dp/B0182JXWZK/ref=sr_1_2?s=electronics&ie=UTF8&qid=1484650772&sr=1-2&keywords=kinobo which should resolve a lot of the issues! To be honest, when not recording it gets it first time, most of the time, let me know if it works for you!

 Q8: Executing shell scripts / commands could be easily done from a Skill, i've created a Skills repo separate to this one where I will put an example of interacting with the shell :)

Hopefully those answers helped clear things up!

**Comment by marksev1** [comment]
Awesome. Thanks for the replies! if pocketsphinx won't work for hotword you could also try this -> https://snowboy.kitt.ai/

I'm gonna keep on watch this project and maybe try to develope something, but will probably require a lot of your guidance :).

**Comment by patrickjquinn** [comment]
Kitt is certainly an option but the ultimate goal is to have the whole thing run offline without online dependencies for speech and voice recognition. PocketShinx is also totally open source which makes it more attractive for tailoring it to the needs of this project! 👍
