### ISSUE TITLE
Hard Coded Rules Support

### ISSUE THREAD

**Issue by timstableford** [patrickjquinn/P-Brain.ai#26]
For the more vague skills like song, they'd be better suited to hard-coded rules rather than classification. It should even improve accuracy for modules that aren't hard-coded.

**Comment by patrickjquinn** [comment]
We can experiment with this, the song module is a good sample to go from, I would prefer to get the NLP stuff working more accurately (pre processing the query instead of running Natural over it raw, might work) but we should certainly give people the option of using rules with skills if they wish.

The only thing we need to ensure is that we keep the code small. Maybe even create a set of contribution guidelines similar to that of the WebKit team "For every 10 lines of code you add, you have to remove or refractor 1 line of code" in order to maintain overall project simplicity :)

**Comment by timstableford** [comment]
The song and timer skills were ones I had in mind initially. I think we could avoid hard rules but the problem as you know is that our data set is currently tiny. I was thinking that hard coding rules could make building an accurate data set of responses simpler.

Do you mean the code for the core server, the code for a skill or the code for a hard coded rule? I tend to agree about the refactoring though :+1:

**Comment by patrickjquinn** [comment]
Yep, that makes sense, we need to flesh out our training set in order to improve accuracy. I vote we test hardcoding for moment and  seeing how elegant (i.e in the smallest amount of code possible) a solution we can come up with.

And i'm referring to the core server here, if you wanted a new skill added to the main repo (as apposed to the standalone skills repo) you would need to refactor or prune code, 10-1 👍

**Comment by patrickjquinn** [comment]
I'll close this for the moment until we can come up with a sample set of rules, i've removed the training set for the 'fact' skill (As the keywords where more than enough to train successfully) as a stop gap for the moment.

**Comment by timstableford** [comment]
I can't say I'm sure why you've closed this. It's still a task to do/investigate/track?

**Comment by patrickjquinn** [comment]
Same as the comment on my other ticket :) i've re-opened this for the mo!

**Comment by timstableford** [comment]
Merged in with #30
