### ISSUE TITLE
Community Feedback Request: Database System

### ISSUE THREAD

**Issue by timstableford** [patrickjquinn/P-Brain.ai#36]
Hi all,

Myself and @patrickjquinn plan to move all the separate configs to a central database, that we'll provide the same API for no matter the result of this.

Behind the scenes, what database system would you like to see as the default database? Would you like something simplistic like dbdata which stores in JSON? Or maybe something more complex like sqlite3 or MySQL? 

Tim

**Comment by syzer** [comment]
configs can use .env
good choice for db is: mongo db, or leveldb

**Comment by patrickjquinn** [comment]
In a move that may alienate some developers, I've had a change of heart. Just looking at @timstableford implementation of SQL lite I realise that as long as ALL db operations are done within a db module (with a common interface) it doesn't really matter which one we go for and to that end, i'm happy to merge @timstableford solution with master.

Partially because SQLite is a fairly self contained solution (Doesn't need a massive instance of MySQL running) and partially because we need this implemented, one way or the other, to move forward with the project. Especially if we want to get the apps live in the app store the possibility of using hosted P-Brain instance.

Are we good to merge your changes @timstableford

**Comment by timstableford** [comment]
@patrickjquinn yes it's okay to merge, but there's a little something I'm working on that will make auth a lot smoother, should be done this evening if you're willing to wait?

I'm making it so it uses HTTP basic auth on the home page for the web app, and then this sets a cookie. It means we don't need the Javascript prompts for usernames and passwords :)

**Comment by patrickjquinn** [comment]
I'm happy to wait :) that sounds like a much welcomed addition! Good stuff

**Comment by timstableford** [comment]
Found a little free time to finish off the changes. They're pushed up to the sqlite_db branch. I'll create a PR for it in a few minutes, give it a thorough test before you merge it in though. I haven't had a chance to test it with multiple users, only as a single user.

**Comment by timstableford** [comment]
PR #38 created. Closing this since @patrickjquinn is happy with the current solution. I imagine we'll re-visit this in the future.
